# Generated by Django 4.2.3 on 2023-07-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trailer_url', models.URLField()),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
