# Generated by Django 4.2.3 on 2023-07-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_description_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='movie_covers/'),
        ),
    ]
