# Generated by Django 4.2.3 on 2023-07-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.TextField(),
        ),
    ]
