# Generated by Django 4.2.3 on 2023-08-01 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_movie_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favorite_of_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_by_users',
            field=models.ManyToManyField(blank=True, related_name='watched_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
